### ISSUE TITLE
VS Code for test should not to register file associations when it starts up

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-test#120]
![image](https://user-images.githubusercontent.com/41773861/146670509-a217851d-c343-4fb6-b460-9b39854715c2.png)

**Comment by connor4312** [comment]
@bpasero this looks the same as the issue I gave to you a couple weeks ago, which I can't find now. Assuming the reporter is correct about vscode-test causing this, is there a way we can ask VS Code to not register itself automatically?

**Comment by bpasero** [comment]
Sorry, but I cannot answer that question. I do not know how macOS decides to fill this menu. We do not have any code that explicitly adds VSCode to this menu as far as I know. We ship a `Info.plist` from our application bundle that is probably causing this because it contains file-type associations to use VSCode for opening:

https://github.com/microsoft/vscode/blob/dd95be52475b84e3ef32b9d18ef0b12d18145fed/build/lib/electron.ts#L102

I would expect that when an older version of VSCode is being deleted/updated, the entry should remove. So here I suspect that the user somehow keeps older versions of VSCode around.

@deepak1556 @joaomoreno for more insights maybe

**Comment by joaomoreno** [comment]
We do nothing here. AFAIK it's macOS's decision to do this based on its automatic probing of functionality described in each app's Info.plist.

**Comment by tjx666** [comment]
Reproduce:

1. clone this project https://github.com/tjx666/vscode-colorize/blob/develop/test/runTest.ts#L14
2. modyfy the vscode version for test
3. run test in shell
4. right click to finder file, you will see a new menu item for the new vscode version

**Comment by joaomoreno** [comment]
@bpasero This is a bug with vscode-test: it's checking for updates in the background. That should always be disabled right? You can pass `--disable-updates` for it.

**Comment by bpasero** [comment]
😱 , the set of flags in https://github.com/microsoft/vscode-test/blob/dcf92b5c4dc28dcab3307f79db4e746d1b1bac5f/lib/runTest.ts#L101-L109 don't seem to match what we are using for our test runs:

https://github.com/microsoft/vscode/blob/bef4dba21f68bbdb8d9f08fe04b2e1858597722b/scripts/test-integration.sh#L71

**Comment by tjx666** [comment]
@connor4312 This issue still exists.
