### ISSUE TITLE
Testing multiple extensions at the same time

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-test#147]
Looks like from some point, the only extensions being "installed" during test is the one specified in `extensionDevelopmentPath`. Is there a way to make the test run against 2+ extensions? Or is there a way to make the test run against extensions installed to `<home path>/.vscode/extensions`?

The context is, we have two extensions that depends on each other, because we need to support remote scenarios. A possible workaround is that we may be able to install one of them with other extension dependencies, and run test against the other, but the location of packaged extensions varies because they are in different pipelines or may be on a local dev machine. So I'm wondering if there's a better way to do this.

**Comment by connor4312** [comment]
You can specify `extensionDevelopmentPath` multiple times to load multiple extensions. However, `extensionTestsPath` can only be specified once. Does that solve your issue?

**Comment by xisui-MSFT** [comment]
How to specify them in runTests() though?

**Comment by connor4312** [comment]
Ah, we should probably allow multiple paths to be passed, a `string | string[]` instead of just `string`.

But for now you could specify them manually using the `launchArgs` option. They're ultimately just shoved in the same array:

https://github.com/microsoft/vscode-test/blob/c6092b087a9c795c6d2097e864ab13e89d825226/lib/runTest.ts#L121-L135

**Comment by xisui-MSFT** [comment]
Tried this and looks like it works for us. I'll try to create a PR today. Thanks!

**Comment by PeterWone** [comment]
@xisui-MSFT I have a very similar scenario in respect of testing against remote workspaces. Reading this thread was very helpful but leaves me wondering how to ensure that the test version of my extension is installed on the remote host, rather than the marketplace release version. Any advice you can offer would be most appreciated; this is the only relevant info I've seen _anywhere_.

**Comment by xisui-MSFT** [comment]
@connor4312 Can you answer Peter's question? I don't have enough knowledge on it.

**Comment by connor4312** [comment]
You can use the VS Code CLI to, for instance `code --install-extension /path/to/custom.vsix`
