### ISSUE TITLE
`runTests` fails to attach to the spawned vscode instance if no extensions are installed

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode-test#192]
When using `resolveCliArgsFromVSCodeExecutablePath` and `resolveCliPathFromVSCodeExecutablePath` for spawning VS Code, I have to install an extension for the tests to work.

If I don't install an extension, the `runTests` function does not attach to the spawned VS Code instance, but instead starts a new one. And this new instance is not started until the child_process spawned one exits. Which it never does unless I quit it manually. Which makes it get stuck in CI:

* https://app.circleci.com/pipelines/github/BetterThanTomorrow/joyride/381/workflows/d6df2ad8-1dda-4f85-ae39-c657223f56c2

My use case is that I want to be able to test my extension both from the filesystem and the VSIX. When I test the filesystem I don't install the the VSIX and provide `extensionDevelopmentPath`. When I test the VSIX I install it and don't provide `extensionDevelopmentPath`.

My workaround is to always install a VSIX. I created a dummy extension for this and install that one for my filesystem extension tests. Then it works:
* https://app.circleci.com/pipelines/github/BetterThanTomorrow/joyride/382/workflows/994bff16-47e3-4cef-bfe3-597a722469d1

## Steps to reproduce

1. Use `resolveCliPathFromVSCodeExecutablePath` or `resolveCliArgsFromVSCodeExecutablePath` to spawn VS Code
2. Don't provide launch args for installing a VSIX

Expected: The test run should execute as normal.

Actual: `runTests` waits for the spawned VS Code to exit before launching a new instance and runs the the tests there.

**Comment by connor4312** [comment]
From what I understand, this is expected behavior. In the version where you didn't install an extension, you just spawned `code-insiders <workspace> --verbose --disable-workspace-trust` using [these lines](https://github.com/BetterThanTomorrow/joyride/commit/8b2351ece55df53c816fe8f46845e39eb15c86a4#diff-42ec4b0c62c24b77a55461e115d450a6673273437db743ac93154080ba183632L42-L52). This then launches the VS Code desktop UI. `spawnSync` will block until that process exits, but unless someone does something to exit VS Code desktop, it'll stay running, and the CLI will not exit until VS Code does. You can try this on your own machine as well.

**Comment by PEZ** [comment]
I've now switch to use `--version` as a launch arg when I don't have an extension to install. I'm all good. Thanks again!
