### ISSUE TITLE
Add instruction for code coverage

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-test#32]
https://github.com/alexandrudima/vscode-extension-coverage-sample

**Comment by aaronpowell** [comment]
Adding my 2c here as I recently added coverage reporting to [my extension](https://github.com/aaronpowell/vscode-profile-switcher) (available in both [Azure Pipelines](https://dev.azure.com/aaronpowell/VS%20Code%20Profile%20Switcher/_build/results?buildId=724&view=codecoverage-tab) and [CodeCov.io](https://codecov.io/gh/aaronpowell/vscode-profile-switcher)).

I was thinking of extracting the code that is used to instrument the code coverage out into a npm package probably to wrap around `runTests` with a function `runTestsWithCoverage` that will check for the `--coverage` cli flag.

The package would also contain the boilerplate for the `suite/index.ts` file, so rather than you having to write the wire up code [like the docs describe](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-runner-script) you just `import run from 'test-with-coverage-package'` and provide it with a Mocha config and paths to glob.

This does mean it is back to being a hard dependency on Mocha, which was changed between `vscode` and `vscode-test`, but I'm not quite sure of the best way to handle it otherwise (maybe the `run` function the package exposes takes a `Promise` which you'd pass in the code like the docs describes and just adds the coverage step at the end).

**Comment by dcermak** [comment]
I have successfully used @connor4312's [`testRunner.ts`](https://github.com/microsoft/vscode-js-debug/blob/master/src/test/testRunner.ts) to get code coverage out of unit tests.

**Comment by seanwu1105** [comment]
Any update for an official instruction?

**Comment by connor4312** [comment]
The next release of the [test CLI](https://github.com/microsoft/vscode-test-cli) has a `--coverage` flag that allows you to collect test coverage for an extension with no additional configuration.
