### ISSUE TITLE
How to run vscode-test runScript from launch.json?

### ISSUE THREAD

**Issue by jcrben** [microsoft/vscode-test#41]
How can we have an entirely synchronized approach so that I'm running tests in the same way using launch.json?

Following up from my comment at https://github.com/microsoft/vscode-test/issues/24#issuecomment-526982117 where I said:
> @octref confused by this - vscode is deprecated per https://www.npmjs.com/package/vscode
> https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode does not discuss how to use vscode-test to run from launch.json, does it?

What's the best way to synchronize the approach so that I can use the same script for both?

I pulled down this repo and tried to run the sample Launch Test and I saw this error:
![image](https://user-images.githubusercontent.com/5614134/64090161-aac04e80-ccfe-11e9-8a3c-29ad42539a6a.png)

Somewhat motivated by https://github.com/prettier/prettier-vscode/pull/940 where there is both the launch.json and `yarn test` ways to run the tests but the launch.json one doesn't work.

**Comment by marvhen** [comment]
Here is a launch configuration that runs runTest.ts:
````
        {
            "name": "Debug runTest.ts",
	    "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/out/test/runTest.js",
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles":[
                "${workspaceRoot}/out/test/runTest.js"
            ],
            "internalConsoleOptions":"openOnSessionStart",
            "preLaunchTask": "npm: compile"
        }
````

...but are you asking how to do this and then additionally run the extension tests as well???   

If so I think since the above is a node process we just need to figure out how to launch the extension host as an additional step.  It would be a different process however right?  The debugger would initially be attached to the node process and then we would need to have it attach to the vscode extension host process for seamless debugging.  I've never heard of a debugger doing this....hmmmm.

**Comment by octref** [comment]
@jcrben There is no one way to run both. One runs your test essentially in the extension host of the Insiders/Stable version of VS Code (and where you can set breakpoints in test and hit them). The other one runs it through CLI, and you can's hit breakpoints there.
