### ISSUE TITLE
Test works locally but not in GitHub Actions

### ISSUE THREAD

**Issue by glenn2223** [microsoft/vscode-test#95]
Here are my test files, which run fine on my local machine:
[runTest.ts](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/src/test/runTest.ts)
[index.ts](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/src/test/index.ts)
[extension.test.ts](https://github.com/glenn2223/vscode-live-sass-compiler/blob/master/src/test/extension.test.ts)

However, when I run them in GitHub actions they fail:
[Run 2262063161](https://github.com/glenn2223/vscode-live-sass-compiler/runs/2262063161?check_suite_focus=true#step:6:21)
[Run 2262079477](https://github.com/glenn2223/vscode-live-sass-compiler/runs/2262079477?check_suite_focus=true#step:6:1)

Is this unsupported or am I missing something?

**Comment by connor4312** [comment]
This does not appear to be an issue with the test runner. Just giving it a glance it looks like you run tests before compilation finishes by having `&` instead of `&&` [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/7ebd969cf3e62a1920a259dee26adc3779f303f1/package.json#L250), which could cause issues.

This is a good question for StackOverflow though 🙂
